spring:
  application:
    name: microservice-gateway-zuul-filter
server:
  port: 8041
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
#zuul:
 # ignore-security-headers: false
management.security.enabled: false