spring:
  application:
    name: microservice-consumer-user-ribben
server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000  #解决第一次请求报超时异常的解决方案