server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine-context
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
     prefer-ip-address: true
     instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}} 
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-USER-RIBBON-WITH-HYSTRIX-CONTEXT
  app-config: microservice-consumer-user-ribbon-with-hystrix-context

turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-USER-RIBBON-WITH-HYSTRIX-CONTEXT: /ribbon/hystrix.stream

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG